{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "apichart.serviceAccountName" . }}
  labels:
{{ include "apichart.labels" . | indent 4 }}
{{- end -}}
